### ISSUE TITLE
URL plugin doesn't emit url.shorting.all, instead it emits url.shorten.all

### ISSUE THREAD

**Issue by sitedyno** [PSchwisow/phergie-irc-plugin-react-url-shorten#5]
I'm not sure when the change happened but URL shortening hasn't worked for me for awhile, just now bothered to look into it.

https://github.com/PSchwisow/phergie-irc-plugin-react-url-shorten/blob/8f268fdf078d73b1735cfecd3b41bc5397a67620/src/Plugin.php#L125

https://github.com/phergie/phergie-irc-plugin-react-url#events

**Comment by PSchwisow** [comment]
It should be fixed in master and in new version 1.0.1.
